# Generated by Django 4.2.10 on 2026-02-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/featured/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-mountain', 'fa-water')", max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.JSONField(default=list, help_text="List of tags as JSON array (e.g., ['meditation', 'mountains', 'spiritual'])"),
        ),
        migrations.AddField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
