# Generated by Django 4.2.10 on 2026-03-11 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_journey_excludes_journey_includes_journey_level_and_more'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImageJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary image for this journey?')),
                ('caption', models.CharField(blank=True, help_text='Specific caption for this journey-image pairing', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this image within the journey')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_journeys', to='gallery.galleryimage')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_images', to='journey.journey')),
            ],
            options={
                'verbose_name': 'Gallery Image - Journey Link',
                'verbose_name_plural': 'Gallery Image - Journey Links',
                'ordering': ['order', 'image__title'],
                'unique_together': {('image', 'journey')},
            },
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='journeys',
            field=models.ManyToManyField(blank=True, help_text='Select journeys this image is associated with', related_name='gallery_images', through='gallery.GalleryImageJourney', to='journey.journey'),
        ),
    ]
