# Generated by Django 4.2.10 on 2026-03-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='highlights',
            field=models.JSONField(default=list, help_text='List of package highlights as JSON array'),
        ),
    ]
