# Generated by Django 4.2.10 on 2026-03-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_journey_excludes_journey_includes_journey_level_and_more'),
        ('destinations', '0002_destination_featured_image_destination_icon_and_more'),
        ('packages', '0002_package_highlights'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-is_featured', 'name']},
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='package',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='color_hex',
            field=models.CharField(blank=True, help_text="Accent color hex code (e.g., '#8E44AD')", max_length=7),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Duration in days (for sorting)', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_display',
            field=models.CharField(blank=True, help_text="Display duration (e.g., '7 days')", max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/featured/'),
        ),
        migrations.AddField(
            model_name='package',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-spa', 'fa-pray')", max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Whether spots are available'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all-levels', 'All Levels')], default='all-levels', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Destinations included in this package', related_name='packages', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='package',
            name='next_start_date',
            field=models.DateField(blank=True, help_text='Next scheduled start date', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='price_display',
            field=models.CharField(blank=True, help_text="Custom price string (e.g., '$1,600 - $2,200')", max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price (for sorting)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price (for sorting)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='quick_facts',
            field=models.JSONField(default=list, help_text='List of package highlights/quick facts as JSON array'),
        ),
        migrations.AddField(
            model_name='package',
            name='savings_text',
            field=models.CharField(blank=True, help_text="Savings information (e.g., 'Save 8% compared to booking separately')", max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Journeys/services included (e.g., Sound Healing, Yoga)', related_name='packages', to='journey.journey'),
        ),
        migrations.AddField(
            model_name='package',
            name='short_description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='package',
            name='spots_left',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(help_text='Full description of the package'),
        ),
    ]
