# Generated by Django 4.2.10 on 2026-02-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='excludes',
            field=models.JSONField(default=list, help_text='List of excluded items as JSON array'),
        ),
        migrations.AddField(
            model_name='journey',
            name='includes',
            field=models.JSONField(default=list, help_text='List of included items as JSON array'),
        ),
        migrations.AddField(
            model_name='journey',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all-levels', 'All Levels')], default='all-levels', max_length=20),
        ),
        migrations.AddField(
            model_name='journey',
            name='quick_facts',
            field=models.JSONField(default=list, help_text='List of quick facts as JSON array'),
        ),
    ]
