# Generated by Django 4.2.10 on 2026-02-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_category', '0001_initial'),
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandise',
            options={'ordering': ['-created_at'], 'verbose_name': 'Merchandise', 'verbose_name_plural': 'Merchandise Items'},
        ),
        migrations.AddField(
            model_name='merchandise',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchandise_items', to='merchandise_category.merchandisecategory'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='merchandise/'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
