# Generated by Django 4.2.10 on 2026-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_alter_merchandise_options_merchandise_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='quick_facts',
            field=models.JSONField(default=list, help_text='List of quick facts as JSON array'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='story',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
